# Generated by Django 4.0.3 on 2022-04-17 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_occasion_pants_top_remove_feeding_cat_delete_cat_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pants',
            options={},
        ),
        migrations.AddField(
            model_name='top',
            name='pants',
            field=models.ManyToManyField(to='main_app.pants'),
        ),
    ]
