# Generated by Django 4.0.3 on 2022-04-17 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_pants_options_top_pants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='top',
            name='pants',
        ),
    ]
