# Generated by Django 4.0.3 on 2022-04-17 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_remove_top_pants'),
    ]

    operations = [
        migrations.AddField(
            model_name='top',
            name='pants',
            field=models.ManyToManyField(to='main_app.pants'),
        ),
    ]
